/* package whatever; // don't place package name! */

import java.util.*;
import java.lang.*;
import java.io.*;
class Ideone
{
	public static void main (String[] args) throws java.lang.Exception
	{
	Scanner n=new Scanner(System.in);
	int num=n.nextInt();
	if(num>0)
	{
		System.out.println("possitive");
		}else if(num<0)
		{System.out.println("negative");
		}else
		{System.out.println("zero");}
		}
}
